language: node_js
node_js:
    - "8.1.2"
env:
    global:
        - NODE_ENV=test
script:
    - npm i
    - npm run lint:all
    - npm run flow
    - npm run coverage
    - npm run build

after_success:
    - codeclimate-test-reporter < coverage/lcov.info
