language: node_js
node_js:
    - "8.1.2"
env:
    global:
        - NODE_ENV=test
before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
script:
    - npm i
    - npm run lint:all
    - npm run flow
    - npm run build
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
